### ISSUE TITLE
Please don't do this :pray:

### ISSUE THREAD

**Issue by dessant** [github-modules/fix-all-the-repositories#2]
package.json is meant to be parsed by machines, and to be formatted according to a spec. There are already enough variations to account for as is, and by encouraging people to not follow the spec, I think this does a disservice for everyone involved.

I agree that having just a string for the repository is prettier, though not as flexible. Have you thought about proposing a syntax change for the `repository` key that also allows specifying a string with a fully qualified URL?

https://docs.npmjs.com/files/package.json#repository

**Comment by zeke** [comment]
> Have you thought about proposing a syntax change

Fully qualified URL strings have always been supported by npm. But you're right that a change to the documentation and the `npm init` behavior should be proposed to address this closer to its source.

**Comment by dessant** [comment]
Yes, it is supported, though only because they try to normalize common syntax issues, we can't expect that from other tools that parse package.json by following the spec outlined in the docs.

Thanks for seeing the issue, and for your GitHub bots!
